#!/usr/bin/env python3
"""
修复/生成 config.json 的脚本
用法: python3 code/fix_config.py --model_type vit_base_patch14_dinov2.lvd142m --img_size 518
"""

import os
import json
import argparse
import pandas as pd
import numpy as np

# ImageNet 标准化参数
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

def fix_config(train_csv, model_dir, model_type, img_size):
    print(f"正在读取标签文件: {train_csv} ...")
    
    if not os.path.exists(train_csv):
        print(f"错误: 找不到文件 {train_csv}")
        return

    # 1. 读取数据并重新构建映射
    df = pd.read_csv(train_csv)
    unique_categories = sorted(df['category_id'].unique())
    num_classes = len(unique_categories)
    
    print(f"检测到 {num_classes} 个类别。")

    # 2. 构建 class_to_idx 并强制转换为 Python 原生 int
    # 这一步至关重要，防止 numpy.int64 导致 JSON 序列化失败
    class_to_idx = {int(cat_id): int(idx) for idx, cat_id in enumerate(unique_categories)}

    # 3. 构建配置字典
    config = {
        'model_type': model_type,
        'num_classes': num_classes,
        'img_size': img_size,
        'class_to_idx': class_to_idx,
        # 如果不知道具体最佳准确率，暂时设为 0.0 或手动填入
        'best_accuracy': 0.0, 
        'normalization': {
            'mean': IMAGENET_MEAN,
            'std': IMAGENET_STD
        },
        'description': 'Config regenerated by fix_config.py'
    }

    # 4. 确保输出目录存在
    if not os.path.exists(model_dir):
        os.makedirs(model_dir, exist_ok=True)

    # 5. 保存文件
    output_path = os.path.join(model_dir, 'config.json')
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=4, ensure_ascii=False)
        print(f"成功! 配置文件已保存至: {output_path}")
        print(f"配置信息: 模型={model_type}, 尺寸={img_size}")
    except Exception as e:
        print(f"保存失败: {e}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='修复 config.json')
    parser.add_argument('--train_csv', type=str, default='./train_labels.csv', help='训练标签文件路径')
    parser.add_argument('--model_dir', type=str, default='./model', help='模型保存目录')
    
    # 默认值设置为我们最后使用的 DINOv2 配置
    parser.add_argument('--model_type', type=str, default='vit_base_patch14_dinov2.lvd142m', 
                        help='模型名称 (例如: vit_base_patch14_dinov2.lvd142m 或 tf_efficientnet_b5_ns)')
    parser.add_argument('--img_size', type=int, default=518, 
                        help='图像输入尺寸 (DINOv2=518, EfficientNet=456)')

    args = parser.parse_args()
    
    fix_config(args.train_csv, args.model_dir, args.model_type, args.img_size)